name: Publish

on:
  push:
    tags: '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      PGP_SIGNING_KEY: ${{ secrets.PGP_SIGNING_KEY }}
      PGP_SIGNING_PASSWORD: ${{ secrets.PGP_SIGNING_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17

      - name: Publish plugin to Sonatype
        run: ./gradlew publish closeAndReleaseSonatypeStagingRepository -PwithoutSample --no-daemon --stacktrace
